foodsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('receitas/', include('receitas.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import include, path

from . import views

# app_name = 'home'
urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

receitas/urls.py
from django.urls import path

from . import views

app_name = 'receitas'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index_receitas'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('<int:pk>/comment/', views.create_review, name='comment'),
    path('category/', views.CategoryListView.as_view(), name='category_index'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='detail_category'),
    path('category/create', views.CategoryCreateView.as_view(), name='create-category'),
]

home/models.py
from django.db import models

# Create your models here.

receitas/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    name = models.CharField(max_length=255)
    ingredients = models.TextField(max_length=2047)
    preparation = models.TextField(max_length=2047)
    poster_url = models.URLField(max_length=200, null=True)
    date = models.DateTimeField(auto_now_add=True)
    last_edit = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name}'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name} by {self.author}'

receitas/forms.py
from django.forms import ModelForm
from .models import Post, Comment

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'ingredients',
            'preparation',
            'poster_url',
        ]

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Resenha',
        }

home/views.py
from django.shortcuts import render

def index(request):
    context = {}
    return render(request, 'home/index.html', context)

def about(request):
    context = {}
    return render(request, 'home/about.html', context)

receitas/views.py
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment, Category
from .forms import CommentForm

class PostListView(generic.ListView):
    model = Post
    template_name = 'receitas/index.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'receitas/detail.html'

class PostCreateView(generic.CreateView):
    model = Post
    template_name = 'receitas/create.html'
    fields = ['name', 'ingredients', 'preparation', 'poster_url']

    def get_success_url(self):
        return reverse('receitas:detail', args=(self.object.id, ))

class PostUpdateView(generic.UpdateView):
    model = Post
    template_name = 'receitas/update.html'
    fields = ['name', 'ingredients', 'preparation', 'poster_url']

    def get_success_url(self):
        return reverse('receitas:detail', args=(self.object.id, ))

class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'receitas/delete.html'
    success_url = reverse_lazy('receitas:index_receitas')

def create_review(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            review_author = form.cleaned_data['author']
            review_text = form.cleaned_data['text']
            review = Comment(author=review_author,
                            text=review_text,
                            post=post)
            review.save()
            return HttpResponseRedirect(
                reverse('receitas:detail', args=(pk, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'receitas/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'receitas/category_index.html'

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'receitas/category.html'

class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'receitas/create_category.html'
    fields = ['name', 'author', 'posts']
    success_url = reverse_lazy('receitas:category_index')

home/templates/home/about.html
{% extends 'base.html' %}

{% block content %}
<h1>Sobre</h1>
Este site foi elaborado por Bruno Abdulklech Sorban para a disciplina PMR3304 -- Sistemas de Informação.
<br>
<b>Registro de Aluno:</b> 11257859

{% endblock content %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block content %}
<main>
<section id='welcome'>

    <h1>Bem vindo ao Comer bem nos faz bem!</h1>

    Aqui você encontrará receitas deliciosas que pode preparar de sua casa. 
    Visite nossa <a href="{% url 'receitas:index_receitas' %}"><b>página de receitas</b></a> para encontrar uma lista com todas disponíveis. 
    Caso esteja na dúvida por qual começar, sugerimos o Apfelstrudel, basta clicar na imagem abaixo para começar.

    <article id='index-card'>
        <a href="receitas/1"><h2>Apfelstrudel</h2></a>
        <a href="receitas/1"><img src="https://i.imgur.com/2OfG8L9.jpeg" alt="Apfelstrudel"></a>
    </article>

</section>
</main>
{% endblock content %}

receitas/templates/receitas/category.html
{% extends 'base.html' %}

{% block content %}
<h1>Categoria {{category.name}} (por {{ category.author }})</h1>
<hr>

<section id='list-cards'>
    {% for post in category.posts.all %}
    <article class="cards">
        <a href="{% url 'receitas:detail' post.id %}"><img src="{{post.poster_url }}" 
            alt="Imagem da Receita {{post.name}}"></a> 
        <h3>{{ post.name }}</h3>
    </article>
    {% endfor %}
</section>
<button class="btn create"><a href="{% url 'receitas:create-category' %}">Crie sua Categoria</a></button>


{% endblock content %}

receitas/templates/receitas/category_index.html
{% extends 'base.html' %}

{% block content %}
<h1>Categorias de Receitas</h1>
<hr>

{% for list in category_list %}

<section class='category'>
    <a href="{% url 'receitas:detail_category' list.id %}"><h2>{{list.name}} (por {{ list.author }}) </h2></a>
    <br>
    <div class='category-div'>
    {% for post in list.posts.all %}
    <article class="cards">
        <a href="{% url 'receitas:detail' post.id %}"><img src="{{post.poster_url }}" 
            alt="Imagem da Receita {{post.name}}"></a> 
        <h3>{{ post.name }}</h3>
    </article>
    {% endfor %}
    </div>
</section>
{% endfor %}

<button class="btn create-category"><a href="{% url 'receitas:create-category' %}">Crie sua Categoria</a></button>

{% endblock content %}

receitas/templates/receitas/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Resenhas {{ post.name }}</h2>

<form action="{% url 'receitas:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Resenha</button>
</form>

<p><a href="{% url 'receitas:detail' post.id %}">Voltar para a página da receita</a></p>
{% endblock content %}

receitas/templates/receitas/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Nova Receita</h2>
<form method="POST" action="{% url 'receitas:create' %}">
    {% csrf_token %}
    <p>
        <label for="id_name">Nome da receita:</label>
        <input type="text" name="name" id="id_name" value="{{ post.name }}" />
    </p>
    Ingredientes:
    <p>
        <textarea type="text" name="ingredients" id="id_ingredients" rows="10" cols="100"></textarea>
    </p>
    Modo de Preparo:
    <p>
        <textarea type="text" name="preparation" id="id_preparation" rows="10" cols="100"></textarea>
    </p>
    <p>
        <label for="id_poster_url">URL do Poster:</label>
        <input type="url" name="poster_url" id="id_poster_url" value="{{ post.poster_url}}" />
    </p>
    <button class="btn submit" type="submit">Criar</button>
</form>

{% endblock content %}

receitas/templates/receitas/create_category.html
{% extends 'base.html' %}

{% block content %}
<h2>Criar Categoria</h2>

<form action="{% url 'receitas:create-category' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

receitas/templates/receitas/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'receitas:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a receita "{{ post.name }}"?
    </p>
    <button class="btn submit" type="submit">Apagar</button>
</form>

{% endblock content %}

receitas/templates/receitas/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ post.name }}</h1>
<main>
    <section class="dados-da-receita">
        <img src="{{ post.poster_url }}" alt="Imagem da receita {{ post.name}}">
        <h2>Ingredientes</h2>
        {{ post.ingredients|safe|escape }} 
        <h2>Modo de Preparo</h2>
        {{ post.preparation|safe|escape }}
        <br><br>
        <b>Incluso nas Categorias: </b>
        <ul>
        {% if post.category_set.all %}
            {% for post in post.category_set.all %}
                <a href="{% url 'receitas:detail_category' post.id %}"><li>{{ post.name }}, por {{ post.author }}</li></a> 
            {% endfor %}
        {% endif %}
        </ul>
        <br>
        <b>Data de criação:</b> {{ post.date|date }}
        <br>
        <b>Última edição:</b> {{ post.last_edit|date }}
        <br>
    </section>

    <section>
            <h2>Resenhas</h2>
        <ul>
            {% if post.comment_set.all %}
            {% for comment in post.comment_set.all %}
            <figure>
                <blockquote>
                    "{{ comment.text }}" - {{ comment.author }}
                </blockquote>
                <figcaption>
                    {{ comment.date|date }}
                </figcaption>
            </figure>
            {% endfor %}
            {% else %}
            <p>Ainda não existem resenhas para essa receita</p>
            {% endif %}
        </ul>

        <hr>
        <button class="btn update"><a href="{% url 'receitas:update' post.id %}">Editar receita</a></button>
        <button class="btn delete"><a href="{% url 'receitas:delete' post.id %}">Deletar receita</a></button>
        <button class="btn comment"><a href="{% url 'receitas:comment' post.id %}">Deixe um comentário</a></button>
        <button class="btn create detail"><a href="{% url 'receitas:create' %}">Adicionar uma nova receita</a></button>
    </section>
</main>
{% endblock content %}

receitas/templates/receitas/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Todas as receitas</h1>
<button class="btn create"><a href="{% url 'receitas:create' %}">Adicionar uma nova receita</a></button>
<hr>
{% if post_list %}
<section id='list-cards'>
    {% for post in post_list %}
    <article class="cards">
        <a href="{% url 'receitas:detail' post.id %}"><img src="{{post.poster_url }}" 
            alt="Imagem da Receita {{post.name}}"></a> 
        <h3>{{ post.name }}</h3>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma receita.</p>
{% endif %}

{% endblock content %}

receitas/templates/receitas/teste.html
<ul>
<li> 3 ovos</li>
<li> 1 lata de leite condensado</li>
<li> 1 lata de leite comum</li>
<li> 1 colher de café de maisena</li>
</ul>

receitas/templates/receitas/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados da Receita {{ post.name }}</h2>
<form method="POST" action="{% url 'receitas:update' post.id%}">
    {% csrf_token %}
    <p>
        <label for="id_name">Nome da receita:</label>
        <input type="text" name="name" id="id_name" value="{{ post.name }}" />
    </p>
    Ingredientes:
    <p>
        <textarea type="text" name="ingredients" id="id_ingredients" rows="10" cols="100">{{ post.ingredients }}</textarea>
    </p>
    Modo de Preparo:
    <p>
        <textarea type="text" name="preparation" id="id_preparation" rows="10" cols="100">{{ post.preparation }}</textarea>
    </p>
    <p>
        <label for="id_poster_url">URL do Poster:</label>
        <input type="url" name="poster_url" id="id_poster_url" value="{{post.poster_url}}" />
    </p>
    <button class="btn submit" type="submit">Atualizar</button>
</form>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id='header'>
        <img src="https://i.imgur.com/nFz8KPw.jpeg" alt="logo">
        <h1><a href="{% url 'index' %}">Comer bem nos faz bem</a></h1>
        <nav>
            <button class="btn home"><a href="{% url 'index' %}">Home</a></button>
            <button class="btn receitas"><a href="{% url 'receitas:index_receitas' %}">Receitas</a></button>
            <button class="btn sobre"><a href="{% url 'receitas:category_index' %}">Categorias</a></button>
            <button class="btn sobre"><a href="{% url 'about' %}">Sobre</a></button>
        </nav>
    </header>

    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>Copyright 2021 Bruno Sorban</p>
    </footer>
</body>

</html>